### ISSUE TITLE
MIDIIOライブラリのチャンネルに対応できていない

### ISSUE THREAD

**Issue by Ryuha-eng** [guno3005/MidiKeyBard#1]
https://openmidiproject.osdn.jp/documentations.html
によるとメッセージ配列の中身は
{0x8n, 0xkk, 0xvv}
n=チャンネル番号(0～F)
となっています。最初の中身はnがチャンネル番号となっているため、
on/offの判定はnを除いてする必要があります。

Midi.ByteToMidiEventTypeMidiメソッドの頭でtype = type & 0xf0;の処理が必要です。

**Comment by guno3005** [comment]
Issueありがとうございます！
現状の実装だとチャンネル番号が0の場合しか動作しないわけですね。
チャンネルは全く考慮できていませんでした…

しかし全チャンネルに対して反応してしまって良いものなのでしょうか？
どのチャンネルを読み取り対象にするか、選択式にする必要があるでしょうか？
MIDIデバイスにあまり詳しくないので、ユーザはどのような使い方をしたときにチャンネル0以外を使いたくなるのか、いまひとつイメージできていない状態です。
（例えばRyuha-engさんはどうしてチャンネルの問題に気付かれたのでしょう？）

関連情報をいただけると助かります

**Comment by guno3005** [comment]
1.2.0で対応したのでクローズします
